### ISSUE TITLE
Encoder message, Electric message

### ISSUE THREAD

**Issue by mikepurvis** [ros/common_msgs#15]
I looked through the [API Reviews](http://wiki.ros.org/sensor_msgs/Reviews); doesn't look like these have been formally discussed before. If there's interest, I can create an API review for either or both.
## Encoder

Similar philosophy to the Range message—a single message which encapsulates the low-level information about an encoder: pulses per radian (fixed), present total pulses, present pulses/s.

It's ultimately expressing the same/similar information to that which ultimately ends up in an Odometry message, but at a lower level. Having Encoder messages published by drive bases with the appropriate transforms might allow for a standard Odometry publisher.
## Electric

Measure of voltage with respect to ground, and current at a particular point. Suggested fields would be voltage_mean, voltage_std, current_mean, current_std, measurement_period.

An obvious outcome of having a common message for this type of thing would be the possibility of more standardized monitoring components—eg, a fuel tank node, something which flags on current spikes, etc.

**Comment by chadrockey** [comment]
-1 on the encoder.  I think encoders have too much variety to end up in common_msgs (there's at least quadrature and analog types).  At the very least, should a message be proposed, it needs to have all encoder ticks present at once or the odometry calculations can be a little iffy (you will turn away from the last encoder reading you received OR you have to do time synchronization of messages - not one of ROS's strong areas).  In addition, encoder readings need to either have accurate timing or never be dropped or pushed out of a queue - not one of the guarantees of a ROS distributed system.

I think a more reasonable approach to a common Odometry publisher would be a C++/python library that you call directly from the driver node.  This way you can reuse Odometry code without needing to overcome the pub/sub limitations.

---

As for voltage, we shouldn't introduce a bunch of statistical fields in a common_msg that will be unused.  Otherwise, people tend to have a habit of wanting to fill them all in, even if they don't have data.  Timestamps are a good example here.  I once saw a message with 4 different timestamp systems (yikes!).

This is very similar to the Android sensors review:

http://wiki.ros.org/sensor_msgs/Reviews/2012-11-16-Low-Cost-Sensor-Roundup_API_Review

https://code.ros.org/gf/project/ros/mailman/?_forum_action=ForumMessageBrowse&thread_id=91558&action=ListThreads&mailman_id=20

If we see a current usecase for Voltage and Current, I'd recommend adding them in this format:
https://github.com/ros/common_msgs/blob/hydro-devel/sensor_msgs/msg/Temperature.msg

As you can see from the review, many people weren't happy with the semantically typed messages preventing applications like what you describe, but I personally think it's important and that it strengthens the interfaces that we do accept.

I'm not sure if there can be substantial reuse of monitoring components across dissimilar robots.  While Clearpath's robots may share many electro-mechanical components - most robots do not.  In general, my rule of thumb has been to standardize if the device is useful without a base (laser scanner, Kinect, Leap Motion, and so on) OR it is a user facing API on different robot types (jointstates, Odometry).  In the case of a fuel tank node or current spikes, this isn't necessarily the case.  What defines a current spike on a Grizzly is not just a simple change of threshold from what defines a current spike on a Kobuki base.

---

A more philosophical comment is that what we (the hardware maintainers) like to see in ROS and what our users want are usually pretty different.  The PR2 mostly did it's hardware debugging in a few robot specific messages (pr2_msgs https://github.com/PR2/pr2_common/blob/hydro-devel/pr2_msgs/msg/PowerBoardState.msg).  It's challenging to avoid exposing too much and confusing the user with obscure interfaces while also being able to log enough information to know when and where something has gone wrong.

The convention has been to have a set of robot specific messages (pr2_msgs, kobuki_msgs, secret_prototype_msgs) and use those as the hardware logging mechanism.  Diagnostics can also be useful as it provides a way to transmit (and log) issues and averaged/parsed data - with the raw data in the *_msgs.

I imagine that Clearpath has quite a few robot configurations, and I would suspect even shared components.  No one has really shared low-level hardware and base configuration/drivers between robot configurations without a lot of pain (PR2-SE, secret_robot_prototype_2).  If you want to discuss this type of thing more, the drivers-sig is probably the most appropriate mailing list to collect others' experiences and thoughts.

https://groups.google.com/forum/#!forum/ros-sig-drivers

**Comment by mikepurvis** [comment]
@chadrockey, thanks for the extensive feedback, much appreciated.

I think one of the confusion points on the encoder is not necessarily wanting a message which would be published standalone, but one which could be included in a larger MCU state type message. Perhaps that's the nail-in-coffin to that, in that `sensor_msgs` messages should be suitable for use standalone.

Your other arguments are sound though; it's likely that there's simply too much hardware variability at the level of detail which interests me. Realistically, the "common interface" to something like an encoder is probably what's actually being measured, which is rotation about an axis—so the correct common message for it is a Quaternion or something else which captures "position, speed, and acceleration of a rotation".

The motivations are similar for an Electric Power message.

I think there's still room for these things, just perhaps as part of the packages containing nodes/libraries to actually process them, rather than in somewhere like common_msgs. For example, a battery_estimator package which then contains a message with the required info. You can either include that message directly elsewhere, or populate it just in time when you make an API call.
