### ISSUE TITLE
std_msgs with header and array version

### ISSUE THREAD

**Issue by maxbader** [ros/common_msgs#49]
Hi

First I read your "Guidelines for submitting to common_msgs" but still I think there is the need for some gerneric msgs I like to discuss.
The pkg should contain std_msg types with a header and as header array version at least for:
int8, uint8, int16, uint16, int32, uint32, int64, uint64, Float32, Float32 and string.  
I think this would prevent a uncontrolled growth of msg types.

Geetings
Markus

e.g.

-------------------------      #UInt64Stamped    -------------------------
Header header 
uint16 data
-------------------------          #UInt64Array     -------------------------
uint16[]  data
------------------------- #UInt64StampedArray -------------------------
Header header 
uint16[]  data

**Comment by tfoote** [comment]
These messages have the same issue as the ones referenced in #21 they are generic datatypes which do not carry semantic meaning which means they cannot be generally interpreted. 

For an example of this, if I was to write an rviz plugin to represent this data, how would I render this value in the 3d window? A well defined message should be self describing, and use the topic only to differentiate the context such as the source etc.

**Comment by maxbader** [comment]
@tfoote 
You are right the semantic meaning it lost. But the semantic meaning will never be fully covert otherwise there is no meaning to remap topics. The semantic meaning is partial covert within the topic under which it is published. Projecting this semantic to the message types is not fully possible. 
Generic types are a way to save working time.

**Comment by chadrockey** [comment]
@maxbader

There are a few more reasons that messages like these should not be used.  One of them is that rosbag migration will migrate any message that shares an MD5 hash.  This means that data were initially recorded in a Float32Stamped but now need to be converted to a new message with another field, MyDebugMessageStamped:

Header header
float32 data
string robot_serial_number

If a developer used rosbag migration to migrate the message, it will convert all messages with Float32Stamped.  So /my_current_score, /cpu_temperature, and /number_of_robots_currently_on_comets all get converted into MyDebugMessageStamped.

---

ROS is also based on the idea of sharing code and sharing datasets to save developers time.  When we do this, we share across the entire world so we have a lot working against us - language barriers, differences in common units, differences in available hardware.

An example would be a controller for a robot arm that slides along a linear rail.  Since this is one dimensional you only need one value, so to save bandwidth and disk space it publishes FloatStamped on topic /total_distance_measurement as the rail doesn't have an absolute reference.  Now let's say someone with a PR2 tries to duplicate the pick and place results by porting the ROS nodes to the PR2.  The only information this researcher/user/developer has to implement something similar to the rail is the one topic.  I purposely worded this one vaguely to show how hard it is to understand these kind of messages.

It could represent:

The current position of the arm on the linear rail, 'total' meaning that this is a sum of two sensors' output to reach the desired accurate measurement.

The total distance traveled by the arm - an integration of the movement of the arm.  'total' here meaning sum of each movement over time.

The total distance the robot COULD travel along the rail, used as an accuracy check for the actual robot position.  If you measured the robot's position on each side, then side_one + robot_width + side_two === the total rail distance measurement.  If recorded that in this topic, it's a good indicator of sensor consistency and accuracy.

[ Any of the above referenced either relative to the starting position OR to the absolute position of the rail.  I purposely used the word 'total' to try to indicate relative, ie:the entirety of the robots motion is captured here relative to the starting position. ]

Once this kind of confusion is compounded through a language barrier (or not), anyone not intimately familiar with this topic cannot use it.  Most likely they will need to find the code that produces the topic to determine the exact meaning.  This also means that if a developer records a bag file with FloatStamped, and then does a minor change to how the value is produced, the old values are now no longer useful or worse, inaccurate and undetectable except by comparing timestamps to commit logs.

---

While it's true that there is some semantic meaning in topics, the messages that are in common_msgs are reviewed to ensure that they are useful even if on their own.  For instance, a Laserscan message may be published on /front_base_laser and then filtered and published on /front_base_laser_filtered.

If we removed the topic names, without a qualitative understanding of the system, I could not tell the filtered scans from the unfiltered ones.  However, I could still:

Produce 2d representations of the laser scans

Produce 3d representations of the laser measurements as the robot moves through space if given the tf transforms (the laser position relative to the other tf frame_ids are all provided here).

Produce time based graphs of the laser scanning both in one scan and between multiple scans.

And most importantly, as a robot developer, I am fundamentally familiar with the concept of a laserscan, so if I need to duplicate results that use a laserscan, I can most likely use any one I have laying around and modify its configuration such that it matches the maximum distance, scan rate, and angle increment of the laser used.  All of that information is provided with the scan to ensure that there is a well defined meaning to the data within.  So even though I may not realize I'm running tests without the laser filtering process, I can still use my normal tools (like RVIZ), and qualitatively see that my Laserscans include a lot more noise, and that perhaps I can email the developers and ask what algorithms were used to filter the laser scans.  None of this would be possible at all if the data were published each beam measurement of the scan in a Float32StampedArray.

---

Remapping topics isn't intended to add semantic meanings.  We add the meanings for convenience and clarity, but the main purpose is to avoid publishing on the same topics more than once and to dynamically change the dataflow of a system without recompiling.  If I ran two laser scan nodes, one from sick and one from hokuyo, they both publish on /scan by default.  I choose to remap them to be /hokuyo_scan and /sick_scan for convenience, but I could as well have mapped them to /2F1AB6F34E7A440E2F8440F166D65356 and /F06FE48D9847DA36764E8159AE151F72.  While there is a system to the remapping that can be used to derive the semantic meaning from the alternate topics, most developers would find it difficult to reverse the md5 hash to determine which laser is on which topic.

---

As for the uncontrolled growth of message types, it's often an indication of severe underuse or over optimizing for uncommon use cases.  For instance, PoseStamped defines both a position and a quaternion orientation.  This is enough to represent the spatial location information for anything in Euclidean coordinates.  Even though the linear rail example above only moves along one dimension, by reporting the current location in a pose message, it instantly resolves all of the confusion regarding the meaning of the message.  The pose of the robot can be visualized in RVIZ and a developer could even use University Of Antarctica's pose_to_acceleration node to compute the approximate accelerations experienced by the robot.  All of this requires little or no work for a developer, there were no new messages defined and no code needed to be written to integrate with the visualization system or even code from another institution on another continent.

And even though I'm sure there have been over a hundred thousand message types defined so far by the entire ROS community, common_msgs has very few of them.  Common_msgs is a curated, shared resource for messages that have proven themselves as meaningful and useful in practice and that have also passed community review for completeness, clarity, and documentation.  It's quite a lot of effort for a message to get accepted into common_msgs, so the community, the process, and time are the bottlenecks preventing these common_msgs from becoming too numerous.

**Comment by maxbader** [comment]
Hi Chad

First thank you for your time, but still there was a good reason to event the std_msg and common_msgs.
I and also see your point and since this is a strategic policy decision I have to go along unless I will build my own framework :-).
But just view things. I started years ago with player/stage with various types of robots and research problems and I tried all big frameworks as well. Now years later I have a highly sophisticated framework but no general representation of a 2D line (Ax + Bx + C) or a line segment with a start and endpoint. If I like to publish a distance value (how far my robot moved) which is one uint64 I should generate a new data-type.
Messages are never self explaining because the context matters as you stated.

I made my point and i am happy to got response, I don't have to like the answer but I am still trying to improve things wherever I can :-)

**Comment by jack-oquin** [comment]
While I thank @maxbader for contributing his idea for expanded generic messages, I strongly agree with @tfoote and @chadrockey that std_msgs should carry semantic meaning and not be generic. 

Therefore, I respectfully request that this issue be closed.
