### ISSUE TITLE
sensor_msgs::convertPointCloudToPointCloud2() crashes

### ISSUE THREAD

**Issue by bmagyar** [ros/common_msgs#6]
I've been running experiments with the tabletop_object_detector and found that the segmentation crashed. Those detection/segmentation nodes are passing pointclouds by sensor_msgs::PointCloud, not PointCloud2. 
The bug always comes when sensor_msgs::convertPointCloudToPointCloud2() is called. I captured the point clouds that are being pushed to the converter at that time.

I set up a node that reproduces the bug. The code is the following:
http://pastebin.com/j6PUF2G7

Bag file with the data that produces the error: (~10MB)
https://www.dropbox.com/s/4fwc0d7d8vihsq0/points_cut2.bag

I managed to fix it by adding 'volatile' to 'int offset' in the function.

**Comment by chadrockey** [comment]
In the future, it's better to immediately create a pull request of the code that works for you.  This automatically opens an issue related to that pull request and ensures that we see exactly what the fix is and that you remember the entire fix.  Can you please create a pull request for the fix and reference this issue there?

It would even better if you created a unit test from your example node that shows the issue.  Then we can make sure it always works.
