### ISSUE TITLE
Why DELETEALL is disable for ros indigo?

### ISSUE THREAD

**Issue by talregev** [ros/common_msgs#98]
In this [line][1], You disable DELETEALL enum.   
I am using indigo ros. And in the [wiki][2], you mention DELETEALL functionality.   
I was surprise that in there is not  DELETEALL enum value on the code.   
So I hack the value from the wiki, and it work! :)   
Why not enable it for all?

[1]:https://github.com/ros/common_msgs/blob/indigo-devel/visualization_msgs/msg/Marker.msg#L19
[2]:http://wiki.ros.org/rviz/DisplayTypes/Marker#Message_Parameters

**Comment by tfoote** [comment]
The enum value was decided to be added after indigo was already released. The message definition was not changed in indigo to maintain stability. The comment was added so that you could use the functionality as you already have.

If we changed the enum, the md5sum of the message would be different and it would invalidate all bag files recorded as well as making it such that indigo packages from before or after the change might not be able to talk to each other. (Most commonly this will hit people playing back a bag file recorded before the change and a subscriber who we compiled after the change.)
